json.executive_wise_this_months_count @executive_wise_this_months_count
json.executive_wise_one_month_before_count @executive_wise_one_month_before_count
json.executive_wise_two_month_before_count @executive_wise_two_month_before_count
json.executive_wise_three_month_before_count @executive_wise_three_month_before_count
json.executive_wise_four_month_before_count @executive_wise_four_month_before_count
json.executive_wise_five_month_before_count @executive_wise_five_month_before_count
json.executive_wise_six_month_before_count @executive_wise_six_month_before_count
json.executive_wise_last_6_months_count @executive_wise_last_6_months_count