json.project_wise_this_months_count @project_wise_this_months_count
json.project_wise_one_month_before_count @project_wise_one_month_before_count
json.project_wise_two_month_before_count @project_wise_two_month_before_count
json.project_wise_three_month_before_count @project_wise_three_month_before_count
json.project_wise_four_month_before_count @project_wise_four_month_before_count
json.project_wise_five_month_before_count @project_wise_five_month_before_count
json.project_wise_six_month_before_count @project_wise_six_month_before_count
json.project_wise_last_6_months_count @project_wise_last_6_months_count